name: Cargo Build & Test

on:
  push:
    branches: [ "otus_algo_hw_02" ]
  pull_request:
    branches: [ "otus_algo_hw_02" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cd ${{github.workspace}}/otus_algo_hw_02 
        cargo test --verbose